### ISSUE TITLE
Error in the BEAST_analyses.R script!

### ISSUE THREAD

**Issue by liamxg** [ONeillMB1/Mtb_Phylogeography#1]
> tree <- read.beast("data/OldWorld_GTR_G_BSP_DiscreteUN_MCC.tree")
> 
> #Group tree by lineages
> 
> tree <- groupClade(tree, node=MRCA(tree, tree@phylo$tip.label[grep("L1", tree@phylo$tip.label)]), "L1")
Error in extract.clade(.data, .node) : the tree has no node labels
>

**Comment by ONeillMB1** [comment]
These scripts were developed years ago under what was then the developmental version of 'ggtree'. It appears the 'groupClade' function is now under 'tidytree' and its input and functionality has since been modified. If you'd like to use the scripts without modification you will need to install an older version of the package (which may not be possible to track down since it was the developers version) or you will have to work with the new packages and sort out how to achieve the same behavior.
